### ISSUE TITLE
Change default branch

### ISSUE THREAD

**Issue by trasher** [galette-community/plugin-stripe#1]
Defaulting on the gh-pages branch seems a bad idea; most users will not understand how to get the plugin source code.

You should be able to do this on your side from repository settings; or I can do it for you if you prefer ;)

**Comment by mpellegrin** [comment]
> Defaulting on the gh-pages branch seems a bad idea; most users will not understand how to get the plugin source code.

I totally agree, but when I pushed the initial commits, Github did it like that (maybe the master => main rollout ?), and i was not able to change it (or didn't find). I wrote about it on the dev mailing list yesterday but you may have missed it.

> You should be able to do this on your side from repository settings; or I can do it for you if you prefer ;)
Yes, it would be nice if you change it as I didn't find where to do it (I can change the Github Pages branch but I didn't find how to change the default branch).

**Comment by trasher** [comment]
> I totally agree, but when I pushed the initial commits, Github did it like that (maybe the master => main rollout ?), and i was not able to change it (or didn't find). I wrote about it on the dev mailing list yesterday but you may have missed it.

I'll change the default branch to develop, and check your ACLs on the repo.

We did not receive that message on the mailing list :/ See february acrhives https://listengine.tuxfamily.org/lists.galette.eu/devel/2021/02/threads.html

> 
> > You should be able to do this on your side from repository settings; or I can do it for you if you prefer ;)
> 
> Yes, it would be nice if you change it as I didn't find where to do it (I can change the Github Pages branch but I didn't find how to change the default branch).

I'll do it, and I'll aslo check your ACLs, maybe something is wrong there. I'll keep you in touch ;)

**Comment by trasher** [comment]
OK, I've switched default branch to develop (that suits all official plugins at least).

You were added as maintainer on the repository, you should have been as admin. I've fixed that :)
